const healthFacilities = [
  "Cek kesehatan dasar: pemeriksaan tensi darah",
  "Cek kesehatan dasar: pemeriksaan gula darah",
  "Infus vitamin booster (immune booster)",
];

export const packageDetailDrafts = [
  {
    code: "SQ-DXB-MHB-20261114",
    name: "Umroh Plus Dubai Program Mahabbah 12 Hari",
    description: "Program Umroh Plus Dubai selama 12 hari dengan penerbangan Emirates, dua pilihan akomodasi Makkah, serta rangkaian pengalaman wisata Dubai setelah agenda ibadah.",
    departureDate: "2026-11-14",
    returnDate: "2026-11-25",
    duration: 12,
    airlineCode: "EK",
    arrivalAirportCode: "JED",
    returnAirportCode: "JED",
    facilities: [
      ...healthFacilities,
      "Hotel Madinah: ODST / Triple / setaraf",
      "Hotel Dubai: Grand Kingsgate Hotel Waterfront",
      "Program Dubai: Dubai Frame, Museum of the Future, Atlantis Hotel, Jumeirah Beach, Burj Al Arab, dan Burj Khalifa",
      "Desert experience: Desert Safari, Dune Bashing, Camel Ride, dan BBQ Dinner",
    ],
    notes: [
      "Draft paket: jumlah seat, itinerary harian, gambar, syarat pendaftaran, biaya di luar paket, dan ketentuan final perlu dilengkapi admin sebelum publikasi",
      "Harga dan susunan program mengikuti materi awal dan dapat berubah setelah konfirmasi operasional",
    ],
    options: [
      {
        name: "Opsi 1 - Winner Inn / Nada Ajyad",
        priceQuad: 37.9,
        priceTriple: 39.9,
        priceDouble: 42.9,
      },
      {
        name: "Opsi 2 - Azka Al-Safa / Maysan Al-Mashaer",
        priceQuad: 39.9,
        priceTriple: 42.9,
        priceDouble: 44.9,
      },
    ],
  },
  {
    code: "SQ-TRK-PRM-20261030",
    name: "Umroh Plus Turki Program Prima 12 Hari",
    description: "Program Umroh Plus Turki selama 12 hari dengan penerbangan Emirates, perjalanan ibadah di Makkah dan Madinah, serta kunjungan ke sejumlah destinasi utama Istanbul.",
    departureDate: "2026-10-30",
    returnDate: "2026-11-10",
    duration: 12,
    airlineCode: "EK",
    arrivalAirportCode: "JED",
    returnAirportCode: "JED",
    facilities: [
      ...healthFacilities,
      "Hotel Makkah: Al-Massa Fayzeen / setaraf",
      "Hotel Madinah: Mukhtara / Triple One / setaraf",
      "Hotel Istanbul: Park Inn Radisson / setaraf",
      "Program Turki: Hagia Sophia, Emirgan Park Tulip, Masjid Abu Ayub, Bosphorus Private Cruise, Masjid Ulucami, Tophane Garden, Blue Mosque, Hippodrome Area, Topkapi Palace Museum, dan Grand Bazaar",
    ],
    notes: [
      "Draft paket: jumlah seat, itinerary harian, gambar, syarat pendaftaran, biaya di luar paket, dan ketentuan final perlu dilengkapi admin sebelum publikasi",
      "Harga dan susunan program mengikuti materi awal dan dapat berubah setelah konfirmasi operasional",
    ],
    options: [
      {
        name: "Pilihan Utama - Al-Massa Fayzeen",
        priceQuad: 40.5,
        priceTriple: 42.5,
        priceDouble: 44.5,
      },
    ],
  },
  {
    code: "SQ-NOV-PRIMA-FAMILY-SMART-20261104",
    name: "Umroh Awal November Prima Family Smart 9 Hari",
    description: "Program Umrah 9 hari dengan harga flash sale dan seat terbatas. Cocok untuk keluarga yang ingin berangkat lebih awal di bulan November dengan pendampingan perjalanan yang praktis dan fasilitas bonus untuk menambah kenyamanan selama di Tanah Suci.",
    departureDate: "2026-11-04",
    returnDate: "2026-11-12",
    duration: 9,
    airlineCode: "SV",
    arrivalAirportCode: "JED",
    returnAirportCode: "JED",
    facilities: [
      "City Tour Thaif",
      "City Tour Makkah dan Madinah",
      "Perlengkapan Umrah**",
      "2x Ayam Al-Baik",
      "Air Zamzam 5 Liter",
      "Transmitter untuk 1x Umrah",
      "Hotel Makkah: Al Massa Fayzeen / setaraf",
      "Hotel Madinah: Mukhtara / ODST / setaraf",
      "Program flash sale dengan seat terbatas",
    ],
    notes: [
      "Harga spesial berlaku selama seat promo masih tersedia.",
      "Perlengkapan Umrah** mengikuti ketentuan dan detail final dari admin.",
      "Harga, ketersediaan seat, susunan hotel, dan fasilitas dapat berubah setelah konfirmasi operasional.",
      "Draft paket: itinerary harian, jumlah seat, gambar flyer, syarat final, dan ketentuan biaya di luar paket perlu dilengkapi admin sebelum publikasi.",
    ],
    registrationRequirements: [
      "KTP dan Kartu Keluarga",
      "Paspor aktif sesuai masa berlaku yang dipersyaratkan",
      "Pas foto 4x6",
      "Mengisi data jamaah sesuai dokumen resmi",
    ],
    termsConditions: [
      "Seat dikunci setelah pembayaran sesuai ketentuan admin dan konfirmasi pembayaran diterima.",
      "Harga promo dapat berakhir apabila kuota flash sale telah terpenuhi.",
      "Nama hotel dan susunan fasilitas dapat menggunakan hotel atau layanan setaraf sesuai ketersediaan operasional.",
      "Biaya di luar paket mengikuti rincian final yang dikonfirmasi sebelum pembayaran.",
    ],
    registrationSteps: [
      "Konsultasikan jadwal, pilihan kamar, dan ketersediaan seat kepada admin.",
      "Kirim data dan dokumen pendaftaran sesuai arahan admin.",
      "Bayar DP melalui rekening resmi Sahabat Qolbu untuk mengunci seat.",
      "Kirim bukti pembayaran dan tunggu konfirmasi dari admin.",
      "Lengkapi persiapan keberangkatan, manasik, dan dokumen perjalanan.",
    ],
    options: [
      {
        name: "Pilihan Utama - Al Massa Fayzeen / Mukhtara ODST",
        priceQuad: 28.9,
        priceTriple: 30.9,
        priceDouble: 32.9,
      },
    ],
  },
  {
    code: "SQ-NOV-MHB-FAMILY-SMART-20261106",
    name: "Umroh Awal November Mahabbah Family Smart 9 Hari",
    description: "Program Umrah 9 hari dengan harga flash sale dan seat terbatas. Pilihan praktis untuk keluarga yang ingin berangkat pada awal November dengan hotel strategis di Makkah dan Madinah serta bonus fasilitas perjalanan.",
    departureDate: "2026-11-06",
    returnDate: "2026-11-14",
    duration: 9,
    airlineCode: "SV",
    arrivalAirportCode: "JED",
    returnAirportCode: "JED",
    facilities: [
      "City Tour Thaif",
      "City Tour Makkah dan Madinah",
      "Perlengkapan Umrah**",
      "2x Ayam Al-Baik",
      "Air Zamzam 5 Liter",
      "Transmitter untuk 1x Umrah",
      "Hotel Makkah: Winner Inn / Nada Ajyad / setaraf",
      "Hotel Madinah: ODST / Triple One / setaraf",
      "Program flash sale dengan seat terbatas",
    ],
    notes: [
      "Harga spesial berlaku selama seat promo masih tersedia.",
      "Perlengkapan Umrah** mengikuti ketentuan dan detail final dari admin.",
      "Harga, ketersediaan seat, susunan hotel, dan fasilitas dapat berubah setelah konfirmasi operasional.",
      "Draft paket: itinerary harian, jumlah seat, gambar flyer, syarat final, dan ketentuan biaya di luar paket perlu dilengkapi admin sebelum publikasi.",
    ],
    registrationRequirements: [
      "KTP dan Kartu Keluarga",
      "Paspor aktif sesuai masa berlaku yang dipersyaratkan",
      "Pas foto 4x6",
      "Mengisi data jamaah sesuai dokumen resmi",
    ],
    termsConditions: [
      "Seat dikunci setelah pembayaran sesuai ketentuan admin dan konfirmasi pembayaran diterima.",
      "Harga promo dapat berakhir apabila kuota flash sale telah terpenuhi.",
      "Nama hotel dan susunan fasilitas dapat menggunakan hotel atau layanan setaraf sesuai ketersediaan operasional.",
      "Biaya di luar paket mengikuti rincian final yang dikonfirmasi sebelum pembayaran.",
    ],
    registrationSteps: [
      "Konsultasikan jadwal, pilihan kamar, dan ketersediaan seat kepada admin.",
      "Kirim data dan dokumen pendaftaran sesuai arahan admin.",
      "Bayar DP melalui rekening resmi Sahabat Qolbu untuk mengunci seat.",
      "Kirim bukti pembayaran dan tunggu konfirmasi dari admin.",
      "Lengkapi persiapan keberangkatan, manasik, dan dokumen perjalanan.",
    ],
    options: [
      {
        name: "Pilihan Utama - Winner Inn / Nada Ajyad - ODST / Triple One",
        priceQuad: 27.5,
        priceTriple: 29.5,
        priceDouble: 31.5,
      },
    ],
  },
  {
    code: "SQ-NOV-MHB-FAMILY-SMART-20261127",
    name: "Umroh Akhir November Mahabbah Family Smart 9 Hari",
    description: "Program Umrah 9 hari dengan harga flash sale dan seat terbatas. Pilihan praktis untuk keluarga yang ingin berangkat pada akhir November dengan hotel strategis di Makkah dan Madinah serta bonus fasilitas perjalanan.",
    departureDate: "2026-11-27",
    returnDate: "2026-12-05",
    duration: 9,
    airlineCode: "SV",
    arrivalAirportCode: "JED",
    returnAirportCode: "JED",
    facilities: [
      "City Tour Thaif",
      "City Tour Makkah dan Madinah",
      "Perlengkapan Umrah**",
      "2x Ayam Al-Baik",
      "Air Zamzam 5 Liter",
      "Transmitter untuk 1x Umrah",
      "Hotel Makkah: Winner Inn / Nada Ajyad / setaraf",
      "Hotel Madinah: ODST / Triple One / setaraf",
      "Program flash sale dengan seat terbatas",
    ],
    notes: [
      "Harga spesial berlaku selama seat promo masih tersedia.",
      "Perlengkapan Umrah** mengikuti ketentuan dan detail final dari admin.",
      "Harga, ketersediaan seat, susunan hotel, dan fasilitas dapat berubah setelah konfirmasi operasional.",
      "Draft paket: itinerary harian, jumlah seat, gambar flyer, syarat final, dan ketentuan biaya di luar paket perlu dilengkapi admin sebelum publikasi.",
    ],
    registrationRequirements: [
      "KTP dan Kartu Keluarga",
      "Paspor aktif sesuai masa berlaku yang dipersyaratkan",
      "Pas foto 4x6",
      "Mengisi data jamaah sesuai dokumen resmi",
    ],
    termsConditions: [
      "Seat dikunci setelah pembayaran sesuai ketentuan admin dan konfirmasi pembayaran diterima.",
      "Harga promo dapat berakhir apabila kuota flash sale telah terpenuhi.",
      "Nama hotel dan susunan fasilitas dapat menggunakan hotel atau layanan setaraf sesuai ketersediaan operasional.",
      "Biaya di luar paket mengikuti rincian final yang dikonfirmasi sebelum pembayaran.",
    ],
    registrationSteps: [
      "Konsultasikan jadwal, pilihan kamar, dan ketersediaan seat kepada admin.",
      "Kirim data dan dokumen pendaftaran sesuai arahan admin.",
      "Bayar DP melalui rekening resmi Sahabat Qolbu untuk mengunci seat.",
      "Kirim bukti pembayaran dan tunggu konfirmasi dari admin.",
      "Lengkapi persiapan keberangkatan, manasik, dan dokumen perjalanan.",
    ],
    options: [
      {
        name: "Pilihan Utama - Winner Inn / Nada Ajyad - ODST / Triple One",
        priceQuad: 27.5,
        priceTriple: 29.5,
        priceDouble: 31.5,
      },
    ],
  },
];
